### ISSUE TITLE
Build error windows with msys

### ISSUE THREAD

**Issue by WolframCrem** [for-loop9/vlither#2]
Hello

i'm trying to build the project on windows with msys, but for some odd reason i'm getting these kind of errors while its linking the app.

```
usr/lib/gcc/x86_64-pc-msys/13.3.0/../../../../x86_64-pc-msys/bin/ld: ../bin/ignite.lib(vk_mem_alloc.o): in function `VmaBlockMetadata_TLSF::~VmaBlockMetadata_TLSF()':
```

**Comment by ezluci** [comment]
You should provide more details...
The only problem I encountered with building on windows was that I had to manually change some parameters in the `make` command. But in the end it worked for me, so you probably did something wrong.
